version: '3'

services:
  web:
    image: tootiredone/lab4_pyapp
    volumes:
      - ./www/media:/app/www/media
      - ./www/:/app/www/
    command: python3 app.py
    ports:
      - "8080:8080"
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    ports:
      - "80:80"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes


